# Generated by Django 4.0.4 on 2022-05-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_videos_topic_videos_updated_alter_videos_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='videoId',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
